---
- name: CleanUp Wsus Server Job
  hosts: all
  
  tasks:
  - name: WSUS CleanUp
    win_shell: Invoke-Command -ComputerName localhost {dir Cert:\LocalMachine\my | ? NotAfter -lt (Get-Date).AddDays(14)}
    register: output

  - debug: var=output.stdout_lines
